### ISSUE TITLE
Sample not building

### ISSUE THREAD

**Issue by sueds** [rookboom/SharpShaders#1]
I just download the samples and there is a bug in it. I'm not familliar enough with with your library to know what' going on but basically the code you sender to the compiler is incorrect there is an error in the translated HLSL

**Comment by rookboom** [comment]
I haven't looked at this in a while but send me the error and I can have a
look.
I think by PostSharp is required by default, so you can try installing that
and see if that makes a difference.
It is not absolutely necessary, but it makes writing the shader structs
much less error prone since you have to then manually  set the field
offsets.

Let me know if that works, otherwise send me the error and which sample you
are  trying to run.

**Comment by sueds** [comment]
You were right I did install it works now. thanks

**Comment by citruslee** [comment]
There is an issue with floating point generation. The shader contains "0f" which is not quite acceptable by the HLSL compiler, you need to define like "0.0f". Could you please elaborate where could I find this section, where it generates the floating point values?
